"""
tests/api/test_auth.py
----------------------
Full coverage unit tests for all authentication endpoints.

Endpoints covered:
  POST /api/v1/auth/register  — create new user
  POST /api/v1/auth/login     — authenticate, receive JWT
  GET  /api/v1/auth/me        — get current user (protected)
  POST /api/v1/auth/logout    — stateless logout (protected)

All tests use an in-memory SQLite database (no Docker required).
JWT tokens are real — generated by core/security.py.
"""

import pytest

REGISTER_URL = "/api/v1/auth/register"
LOGIN_URL = "/api/v1/auth/login"
ME_URL = "/api/v1/auth/me"
LOGOUT_URL = "/api/v1/auth/logout"

VALID_USER = {
    "email": "test@agri.com",
    "password": "securepass123",
    "role": "viewer",
}


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def register_and_login(client, user=None) -> str:
    """Register a user and return a valid JWT token."""
    payload = user or VALID_USER
    client.post(REGISTER_URL, json=payload)
    resp = client.post(LOGIN_URL, json={
        "email": payload["email"],
        "password": payload["password"],
    })
    return resp.json()["data"]["access_token"]


# ---------------------------------------------------------------------------
# POST /auth/register
# ---------------------------------------------------------------------------

class TestRegister:
    def test_success_returns_201(self, client):
        """Successful registration returns HTTP 201."""
        response = client.post(REGISTER_URL, json=VALID_USER)
        assert response.status_code == 201

    def test_success_response_shape(self, client):
        """Response must contain: status, data, message."""
        response = client.post(REGISTER_URL, json=VALID_USER)
        body = response.json()
        assert body["status"] == "success"
        assert "data" in body
        assert "message" in body

    def test_success_user_data_returned(self, client):
        """User data in response must match what was sent."""
        response = client.post(REGISTER_URL, json=VALID_USER)
        data = response.json()["data"]
        assert data["email"] == VALID_USER["email"]
        assert data["role"] == VALID_USER["role"]
        assert "user_id" in data

    def test_password_not_in_response(self, client):
        """Password hash must NEVER appear in any response."""
        response = client.post(REGISTER_URL, json=VALID_USER)
        body_str = response.text
        assert "password" not in body_str
        assert "hash" not in body_str

    def test_duplicate_email_returns_400(self, client):
        """Registering the same email twice must return 400."""
        client.post(REGISTER_URL, json=VALID_USER)
        response = client.post(REGISTER_URL, json=VALID_USER)
        assert response.status_code == 400

    def test_duplicate_email_error_message(self, client):
        """Error response must be informative."""
        client.post(REGISTER_URL, json=VALID_USER)
        response = client.post(REGISTER_URL, json=VALID_USER)
        body = response.json()
        assert "detail" in body

    def test_invalid_email_returns_422(self, client):
        """Pydantic validation: invalid email format."""
        payload = {**VALID_USER, "email": "not-an-email"}
        response = client.post(REGISTER_URL, json=payload)
        assert response.status_code == 422

    def test_password_too_short_returns_422(self, client):
        """Pydantic validation: password under 8 characters."""
        payload = {**VALID_USER, "password": "short"}
        response = client.post(REGISTER_URL, json=payload)
        assert response.status_code == 422

    def test_invalid_role_returns_422(self, client):
        """Pydantic validation: role must be admin | analyst | viewer."""
        payload = {**VALID_USER, "role": "superuser"}
        response = client.post(REGISTER_URL, json=payload)
        assert response.status_code == 422

    def test_missing_email_returns_422(self, client):
        """Missing required fields should return 422."""
        response = client.post(REGISTER_URL, json={"password": "pass1234"})
        assert response.status_code == 422

    def test_missing_password_returns_422(self, client):
        """Missing required fields should return 422."""
        response = client.post(REGISTER_URL, json={"email": "a@b.com"})
        assert response.status_code == 422

    def test_admin_role_allowed(self, client):
        """Admin role must be accepted during registration."""
        payload = {**VALID_USER, "role": "admin"}
        response = client.post(REGISTER_URL, json=payload)
        assert response.status_code == 201

    def test_default_role_is_viewer(self, client):
        """If role is omitted, default should be 'viewer'."""
        payload = {"email": "viewer@agri.com", "password": "password123"}
        response = client.post(REGISTER_URL, json=payload)
        assert response.status_code == 201
        assert response.json()["data"]["role"] == "viewer"


# ---------------------------------------------------------------------------
# POST /auth/login
# ---------------------------------------------------------------------------

class TestLogin:
    def test_success_returns_200(self, client):
        """Successful login returns HTTP 200."""
        client.post(REGISTER_URL, json=VALID_USER)
        response = client.post(LOGIN_URL, json={
            "email": VALID_USER["email"],
            "password": VALID_USER["password"],
        })
        assert response.status_code == 200

    def test_success_returns_token(self, client):
        """Login response must contain access_token and token_type."""
        client.post(REGISTER_URL, json=VALID_USER)
        response = client.post(LOGIN_URL, json={
            "email": VALID_USER["email"],
            "password": VALID_USER["password"],
        })
        data = response.json()["data"]
        assert "access_token" in data
        assert data["token_type"] == "bearer"

    def test_token_is_non_empty_string(self, client):
        """Access token must be a non-empty string."""
        token = register_and_login(client)
        assert isinstance(token, str)
        assert len(token) > 0

    def test_wrong_password_returns_401(self, client):
        """Wrong password must return 401 Unauthorized."""
        client.post(REGISTER_URL, json=VALID_USER)
        response = client.post(LOGIN_URL, json={
            "email": VALID_USER["email"],
            "password": "wrongpassword",
        })
        assert response.status_code == 401

    def test_wrong_email_returns_401(self, client):
        """Non-existent email must return 401 Unauthorized."""
        response = client.post(LOGIN_URL, json={
            "email": "nobody@agri.com",
            "password": "whatever123",
        })
        assert response.status_code == 401

    def test_missing_fields_returns_422(self, client):
        """Login with empty body must fail validation."""
        response = client.post(LOGIN_URL, json={})
        assert response.status_code == 422

    def test_invalid_email_format_returns_422(self, client):
        """Login with malformed email must fail Pydantic validation."""
        response = client.post(LOGIN_URL, json={
            "email": "bad-email",
            "password": "password123",
        })
        assert response.status_code == 422


# ---------------------------------------------------------------------------
# GET /auth/me
# ---------------------------------------------------------------------------

class TestMe:
    def test_success_returns_200(self, client):
        """GET /me with valid token must return 200."""
        token = register_and_login(client)
        response = client.get(ME_URL, headers={"Authorization": f"Bearer {token}"})
        assert response.status_code == 200

    def test_success_returns_user_data(self, client):
        """Response must contain the authenticated user's info."""
        token = register_and_login(client)
        response = client.get(ME_URL, headers={"Authorization": f"Bearer {token}"})
        data = response.json()["data"]
        assert data["email"] == VALID_USER["email"]
        assert "user_id" in data
        assert "role" in data

    def test_no_token_returns_401(self, client):
        """Request without Authorization header must return 401."""
        response = client.get(ME_URL)
        assert response.status_code == 401

    def test_invalid_token_returns_401(self, client):
        """Tampered or garbage token must return 401."""
        response = client.get(ME_URL, headers={"Authorization": "Bearer invalidtoken.abc.def"})
        assert response.status_code == 401

    def test_expired_token_returns_401(self, client):
        """An expired token (manually crafted) must be rejected."""
        from datetime import timedelta
        from app.core.security import create_access_token
        expired_token = create_access_token(
            data={"sub": "9999"},
            expires_delta=timedelta(seconds=-1),  # already expired
        )
        response = client.get(ME_URL, headers={"Authorization": f"Bearer {expired_token}"})
        assert response.status_code == 401

    def test_password_not_in_me_response(self, client):
        """Password hash must never appear in /me response."""
        token = register_and_login(client)
        response = client.get(ME_URL, headers={"Authorization": f"Bearer {token}"})
        assert "password" not in response.text
        assert "hash" not in response.text


# ---------------------------------------------------------------------------
# POST /auth/logout
# ---------------------------------------------------------------------------

class TestLogout:
    def test_success_returns_200(self, client):
        """Logout with valid token must return 200."""
        token = register_and_login(client)
        response = client.post(LOGOUT_URL, headers={"Authorization": f"Bearer {token}"})
        assert response.status_code == 200

    def test_success_response_shape(self, client):
        """Logout response must include status=success."""
        token = register_and_login(client)
        response = client.post(LOGOUT_URL, headers={"Authorization": f"Bearer {token}"})
        body = response.json()
        assert body["status"] == "success"

    def test_no_token_returns_401(self, client):
        """Logout without a token must be rejected."""
        response = client.post(LOGOUT_URL)
        assert response.status_code == 401
